"""Add new columns to tasks

Revision ID: 409bfa0789ad
Revises: 4e2cace3bbb3
Create Date: 2020-05-08 12:25:50.821407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409bfa0789ad'
down_revision = '4e2cace3bbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('taskType', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('completedDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'taskType')
    # ### end Alembic commands ###
