"""Add type and completion columns to Task model

Revision ID: a90b88f588c2
Revises: 1a08822a6a6b
Create Date: 2020-05-08 11:54:12.503602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90b88f588c2'
down_revision = '1a08822a6a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completedDate', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('taskType', sa.String(length=64), nullable=False, default="recurring"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'taskType')
    op.drop_column('tasks', 'completedDate')
    # ### end Alembic commands ###
