"""Add parcel description field

Revision ID: f6d674c41734
Revises: 51b1fe6ff1dc
Create Date: 2020-05-04 14:51:43.904852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d674c41734'
down_revision = '51b1fe6ff1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcelInfo', sa.Column('description', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcelInfo', 'description')
    # ### end Alembic commands ###
